# Copyright (c) 2014, 2015, 2016, 2017 Wieland Hoffmann, MetaBrainz Foundation
# License: MIT, see LICENSE for details

"""
This package contains core entities that are used in the search index and
various tools for working with them.
"""

# Below are the defininitions for all search entities. Each defines a set of
# fields and some additional parameters. Entities have paths associated with
# them, which define the way along which values of fields can be found. The
# paths are created manually by reading through the *Index.java files in
# https://github.com/metabrainz/search-server/tree/master/index/src/main/java/org/musicbrainz/search/index
# and figuring out which SQL statements are used for which search field.
#
# Some entities contain an `extrapaths` argument, which has the paths that are
# not stored in search fields, but are in the XML generated by the wscompat
# module. We don't want to interact with the database in the wscompat module
# since it will be very inefficient: for each entity/row that it processes, it
# would fetch additional required data and only for that single entity. So for
# N entites that are processed by the wscompat module, we'd have an additional
# N accesses to the database.
#
# Paths might need to be updated as a part of schema changes in the
# MusicBrainz server.

from collections import OrderedDict, defaultdict

from mbdata import models
from sqlalchemy.orm import class_mapper
from sqlalchemy.orm.descriptor_props import CompositeProperty
from sqlalchemy.orm.properties import ColumnProperty, RelationshipProperty

from sir.schema import modelext, queryext
from sir.schema import transformfuncs as tfs
from sir.schema.searchentities import SearchEntity as E
from sir.schema.searchentities import SearchField as F

SearchAnnotation = E(
    modelext.CustomAnnotation,
    [
        F("id", "id"),
        F(
            "entity",
            [
                "areas.area.gid",
                "artists.artist.gid",
                "events.event.gid",
                "instruments.instrument.gid",
                "labels.label.gid",
                "places.place.gid",
                "recordings.recording.gid",
                "releases.release.gid",
                "release_groups.release_group.gid",
                "series.series.gid",
                "works.work.gid",
            ],
        ),
        F(
            "name",
            [
                "areas.area.name",
                "artists.artist.name",
                "events.event.name",
                "instruments.instrument.name",
                "labels.label.name",
                "places.place.name",
                "recordings.recording.name",
                "releases.release.name",
                "release_groups.release_group.name",
                "series.series.name",
                "works.work.name",
            ],
        ),
        F("text", "text"),
        F(
            "type",
            [
                "areas.__tablename__",
                "artists.__tablename__",
                "events.__tablename__",
                "instruments.__tablename__",
                "labels.__tablename__",
                "places.__tablename__",
                "recordings.__tablename__",
                "releases.__tablename__",
                "release_groups.__tablename__",
                "series.__tablename__",
                "works.__tablename__",
            ],
            transformfunc=tfs.annotation_type,
        ),
    ],
    1.7,
    extraquery=queryext.filter_valid_annotations,
)


SearchArea = E(
    modelext.CustomArea,
    [
        F("mbid", "gid"),
        F("area", "name"),
        F("comment", "comment"),
        F("begin", "begin_date", transformfunc=tfs.index_partialdate_to_string),
        F("end", "end_date", transformfunc=tfs.index_partialdate_to_string),
        F("ended", "ended", transformfunc=tfs.ended_to_string),
        F("iso1", "iso_3166_1_codes.code"),
        F("iso2", "iso_3166_2_codes.code"),
        F("iso3", "iso_3166_3_codes.code"),
        F("sortname", "aliases.sort_name"),
        F(
            "ref_count",
            ["place_count", "label_count", "artist_count"],
            transformfunc=tfs.integer_sum,
            trigger=False,
        ),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F("alias", "aliases.name", preserve_og=True),
        F(
            "alias_json",
            [
                "aliases.name",
                "aliases.sort_name",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
                "aliases.type.name",
                "aliases.type.gid",
            ],
            objconverter=tfs.aliases_to_json,
        ),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
        F(
            "rel_json",
            [
                "area_links.entity0.name",
                "area_links.entity0.gid",
                "area_links.entity0.begin_date",
                "area_links.entity0.end_date",
                "area_links.entity0.ended",
                "area_links.entity0.type.gid",
                "area_links.entity0.type.name",
                "area_links.link.link_type.name",
                "area_links.link.link_type.gid",
            ],
            objconverter=tfs.area_relations_to_json,
        ),
    ],
    1.7,
)


SearchArtist = E(modelext.CustomArtist, [
    F("mbid", "gid"),
    F("artist", "name"),
    F("sortname", "sort_name"),
    F("comment", "comment"),

    F("type", "type.name"),
    F("type_gid", "type.gid"),

    F("gender_name", "gender.name", transformfunc=tfs.str_list_to_lowercase),
    F("gender_gid", "gender.gid"),

    F("begin", "begin_date", transformfunc=tfs.index_partialdate_to_string),
    F("end", "end_date", transformfunc=tfs.index_partialdate_to_string),
    F("ended", "ended", transformfunc=tfs.ended_to_string),

    F("country", "area.iso_3166_1_codes.code"),

    F("area", ["area.name", "area.aliases.name"]),
    F("area_name", "area.name"),
    F("area_gid", "area.gid"),
    F("area_begindate", "area.begin_date", transformfunc=tfs.index_partialdate_to_string),
    F("area_enddate", "area.end_date", transformfunc=tfs.index_partialdate_to_string),
    F("area_ended", "area.ended", transformfunc=tfs.ended_to_string),
    F("area_type", "area.type.name"),
    F("area_type_gid", "area.type.gid"),

    F("beginarea", ["begin_area.name", "begin_area.aliases.name"]),
    F("beginarea_name", "begin_area.name"),
    F("beginarea_gid", "begin_area.gid"),
    F("beginarea_begindate", "begin_area.begin_date", transformfunc=tfs.index_partialdate_to_string),
    F("beginarea_enddate", "begin_area.end_date", transformfunc=tfs.index_partialdate_to_string),
    F("beginarea_ended", "begin_area.ended", transformfunc=tfs.ended_to_string),
    F("beginarea_type", "begin_area.type.name"),
    F("beginarea_type_gid", "begin_area.type.gid"),

    F("endarea", ["end_area.name", "end_area.aliases.name"]),
    F("endarea_name", "end_area.name"),
    F("endarea_gid", "end_area.gid"),
    F("endarea_begindate", "end_area.begin_date", transformfunc=tfs.index_partialdate_to_string),
    F("endarea_enddate", "end_area.end_date", transformfunc=tfs.index_partialdate_to_string),
    F("endarea_ended", "end_area.ended", transformfunc=tfs.ended_to_string),
    F("endarea_type", "end_area.type.name"),
    F("endarea_type_gid", "end_area.type.gid"),

    F("alias", "aliases.name", preserve_og=True),
    F("alias_json",
      ["aliases.name", "aliases.sort_name", "aliases.locale",
       "aliases.primary_for_locale", "aliases.begin_date", "aliases.end_date",
       "aliases.type.name", "aliases.type.gid"],
      objconverter=tfs.aliases_to_json),
    # Does not require a trigger since this will get updated on an alias update
    F("primary_alias", "primary_aliases", trigger=False),

    F("ipi", "ipis.ipi"),
    F("isni", "isnis.isni"),

    F("tag", "tags.tag.name", preserve_og=True),
    F("tag_count", "tags.count", preserve_og=True),

    F("ref_count", "artist_credit_names.artist_credit.ref_count",
      transformfunc=sum, trigger=False),
],
    1.7,
)


SearchCDStub = E(
    modelext.CustomReleaseRaw,
    [
        F("id", "id"),
        F("title", "title"),
        F("artist", "artist"),
        F("comment", "comment"),
        F("barcode", "barcode"),
        F("added", "added", transformfunc=tfs.datetime_to_timestamp),
        F("tracks", "discids.track_count"),
        F("discid", "discids.discid"),
    ],
    1.7,
)


SearchEditor = E(
    models.Editor,
    [F("id", "id"), F("bio", "bio"), F("editor", "name")],
    1.7,
)


SearchEvent = E(
    modelext.CustomEvent,
    [
        F("mbid", "gid"),
        F("event", "name"),
        F("comment", "comment"),
        F("begin", "begin_date", transformfunc=tfs.index_partialdate_to_string),
        F("end", "end_date", transformfunc=tfs.index_partialdate_to_string),
        F("ended", "ended", transformfunc=tfs.ended_to_string),
        F("time", "time", transformfunc=tfs.index_time_to_string),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F("alias", "aliases.name", preserve_og=True),
        F(
            "alias_json",
            [
                "aliases.name",
                "aliases.sort_name",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
                "aliases.type.name",
                "aliases.type.gid",
            ],
            objconverter=tfs.aliases_to_json,
        ),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
        F("aid", "area_links.entity0.gid"),
        F("area", "area_links.entity0.name"),
        F("arid", "artist_links.entity0.gid", transformfunc=tfs.uuid_list_to_str_list),
        F("artist", "artist_links.entity0.name"),
        F("pid", "place_links.entity1.gid"),
        F("place", "place_links.entity1.name"),
        F(
            "rel_json",
            [
                "area_links.entity0.gid",
                "area_links.entity0.name",
                "area_links.link.link_type.name",
                "area_links.link.link_type.gid",
                "artist_links.entity0.gid",
                "artist_links.entity0.name",
                "artist_links.entity0.sort_name",
                "artist_links.entity0.comment",
                "artist_links.link.link_type.name",
                "artist_links.link.link_type.gid",
                "place_links.entity1.gid",
                "place_links.entity1.name",
                "place_links.link.link_type.name",
                "place_links.link.link_type.gid",
            ],
            objconverter=tfs.event_relations_to_json,
        ),
    ],
    1.7,
)


SearchInstrument = E(
    modelext.CustomInstrument,
    [
        F("alias", "aliases.name"),
        F("comment", "comment"),
        F("description", "description"),
        F("mbid", "gid"),
        F("instrument", "name"),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F(
            "alias_json",
            [
                "aliases.type.name",
                "aliases.type.id",
                "aliases.sort_name",
                "aliases.type.gid",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
            ],
            objconverter=tfs.aliases_to_json,
        ),
    ],
    1.7,
)


SearchLabel = E(
    modelext.CustomLabel,
    [
        F("mbid", "gid"),
        F("label", "name"),
        F("sortname", "aliases.sort_name"),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F("area", ["area.name", "area.aliases.name"]),
        F("area_name", "area.name"),
        F("area_gid", "area.gid"),
        F("area_begindate", "area.begin_date", transformfunc=tfs.index_partialdate_to_string),
        F("area_enddate", "area.end_date", transformfunc=tfs.index_partialdate_to_string),
        F("area_ended", "area.ended", transformfunc=tfs.ended_to_string),
        F("area_type_gid", "area.type.gid"),
        F("area_type", "area.type.name"),
        F("country", "area.iso_3166_1_codes.code"),
        F("code", "label_code"),
        F("alias", "aliases.name"),
        F(
            "alias_json",
            [
                "aliases.type.name",
                "aliases.type.id",
                "aliases.type.gid",
                "aliases.sort_name",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
            ],
            objconverter=tfs.aliases_to_json,
        ),
        F("ipi", "ipis.ipi"),
        F("isni", "isnis.isni"),
        F("comment", "comment"),
        F("begin", "begin_date", transformfunc=tfs.index_partialdate_to_string),
        F("end", "end_date", transformfunc=tfs.index_partialdate_to_string),
        F("ended", "ended", transformfunc=tfs.ended_to_string),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
        F("release_count", "release_count", transformfunc=tfs.integer_sum, trigger=False),
    ],
    1.7,
)


SearchPlace = E(
    modelext.CustomPlace,
    [
        F("mbid", "gid"),
        F("place", "name"),
        F("address", "address"),
        F("comment", "comment"),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F("area", ["area.name", "area.aliases.name"]),
        F("area_name", "area.name"),
        F("area_gid", "area.gid"),
        F("area_begindate", "area.begin_date", transformfunc=tfs.index_partialdate_to_string),
        F("area_enddate", "area.end_date", transformfunc=tfs.index_partialdate_to_string),
        F("area_ended", "area.ended", transformfunc=tfs.ended_to_string),
        F("area_type_gid", "area.type.gid"),
        F("area_type", "area.type.name"),
        F("alias", "aliases.name"),
        F(
            "alias_json",
            [
                "aliases.type.name",
                "aliases.type.id",
                "aliases.type.gid",
                "aliases.sort_name",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
            ],
            objconverter=tfs.aliases_to_json,
        ),
        F("begin", "begin_date", transformfunc=tfs.index_partialdate_to_string),
        F("end", "end_date", transformfunc=tfs.index_partialdate_to_string),
        F("ended", "ended", transformfunc=tfs.ended_to_string),
        F("lat", "coordinates", transformfunc=tfs.lat),
        F("long", "coordinates", transformfunc=tfs.long),
    ],
    1.7,
)


SearchRecording = E(
    modelext.CustomRecording,
    [
        F("mbid", "gid"),
        F("recording", "name"),
        F("comment", "comment"),
        F("alias", "aliases.name"),
        F("arid", "artist_credit.artists.artist.gid", transformfunc=tfs.uuid_list_to_str_list),
        F("artist", "artist_credit.name"),
        F("artistname", "artist_credit.artists.artist.name"),
        F("creditname", "artist_credit.artists.name"),
        F(
            "artist_credit_json",
            [
                "artist_credit.gid",
                "artist_credit.artists.name",
                "artist_credit.artists.join_phrase",
                "artist_credit.artists.artist.gid",
                "artist_credit.artists.artist.name",
                "artist_credit.artists.artist.comment",
                "artist_credit.artists.artist.sort_name",
                "artist_credit.artists.artist.aliases.name",
                "artist_credit.artists.artist.aliases.sort_name",
                "artist_credit.artists.artist.aliases.locale",
                "artist_credit.artists.artist.aliases.primary_for_locale",
                "artist_credit.artists.artist.aliases.begin_date",
                "artist_credit.artists.artist.aliases.end_date",
                "artist_credit.artists.artist.aliases.type.name",
                "artist_credit.artists.artist.aliases.type.id",
                "artist_credit.artists.artist.aliases.type.gid",
            ],
            objconverter=tfs.recording_artist_credit_to_json,
        ),
        F("dur", "length"),
        F("qdur", "length", transformfunc=tfs.qdur),
        F(
            "firstreleasedate",
            "first_release_date.date",
            transformfunc=tfs.index_partialdate_to_string,
        ),
        F("isrc", "isrcs.isrc"),
        F("video", "video", transformfunc=tfs.boolean),
        F("country", "tracks.medium.release.country_dates.country.area.iso_3166_1_codes.code"),
        F(
            "date",
            "tracks.medium.release.country_dates.date",
            transformfunc=tfs.index_partialdate_to_string,
        ),
        F("format", "tracks.medium.format.name"),
        F("number", "tracks.number"),
        F("position", "tracks.medium.position"),
        F("primarytype", "tracks.medium.release.release_group.type.name"),
        F("reid", "tracks.medium.release.gid"),
        F("release", "tracks.medium.release.name"),
        F("rgid", "tracks.medium.release.release_group.gid"),
        F(
            "secondarytype",
            "tracks.medium.release.release_group.secondary_types.secondary_type.name",
        ),
        F("status", "tracks.medium.release.status.name"),
        F("tid", "tracks.gid"),
        F("tnum", "tracks.position"),
        F("tracks", "tracks.medium.track_count"),
        F("tracksrelease", "tracks.medium.release.mediums.track_count", transformfunc=sum),
        F(
            "release_json",
            [
                "tracks.gid",
                "tracks.name",
                "tracks.number",
                "tracks.position",
                "tracks.length",
                "tracks.medium.gid",
                "tracks.medium.position",
                "tracks.medium.track_count",
                "tracks.medium.format.name",
                "tracks.medium.release.gid",
                "tracks.medium.release.name",
                "tracks.medium.release.comment",
                "tracks.medium.release.artist_credit.gid",
                "tracks.medium.release.artist_credit.artists.name",
                "tracks.medium.release.artist_credit.artists.join_phrase",
                "tracks.medium.release.artist_credit.artists.artist.gid",
                "tracks.medium.release.artist_credit.artists.artist.name",
                "tracks.medium.release.artist_credit.artists.artist.comment",
                "tracks.medium.release.artist_credit.artists.artist.sort_name",
                "tracks.medium.release.country_dates.date",
                "tracks.medium.release.country_dates.country.area.gid",
                "tracks.medium.release.country_dates.country.area.name",
                "tracks.medium.release.country_dates.country.area.iso_3166_1_codes.code",
                "tracks.medium.release.mediums.track_count",
                "tracks.medium.release.release_group.gid",
                "tracks.medium.release.release_group.name",
                "tracks.medium.release.release_group.comment",
                "tracks.medium.release.release_group.type.name",
                "tracks.medium.release.release_group.type.gid",
                "tracks.medium.release.release_group.secondary_types.secondary_type.name",
                "tracks.medium.release.release_group.secondary_types.secondary_type.gid",
                "tracks.medium.release.status.name",
                "tracks.medium.release.status.gid",
            ],
            objconverter=tfs.recording_releases_to_json,
        ),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
    ],
    1.7,
)


SearchRelease = E(
    modelext.CustomRelease,
    [
        F("mbid", "gid"),
        F("release", "name"),
        F("alias", "aliases.name"),
        F("arid", "artist_credit.artists.artist.gid", transformfunc=tfs.uuid_list_to_str_list),
        F("artist", "artist_credit.name"),
        F("artistname", "artist_credit.artists.artist.name"),
        F("creditname", "artist_credit.artists.name"),
        F(
            "artist_credit_json",
            [
                "artist_credit.gid",
                "artist_credit.artists.name",
                "artist_credit.artists.join_phrase",
                "artist_credit.artists.artist.gid",
                "artist_credit.artists.artist.name",
                "artist_credit.artists.artist.comment",
                "artist_credit.artists.artist.sort_name",
            ],
            objconverter=tfs.release_artist_credit_to_json,
        ),
        F("asin", "asin.amazon_asin"),
        F("barcode", "barcode", transformfunc=tfs.fill_none),
        F("barcode_none", "barcode", objconverter=tfs.release_barcode_none),
        F("comment", "comment"),
        F("packaging", "packaging.name"),
        F("packaging_gid", "packaging.gid"),
        F("country", "country_dates.country.area.iso_3166_1_codes.code"),
        F("date", "country_dates.date", transformfunc=tfs.index_partialdate_to_string),
        F(
            "release_event_json",
            [
                "country_dates.date",
                "country_dates.country.area.gid",
                "country_dates.country.area.name",
                "country_dates.country.area.iso_3166_1_codes.code",
            ],
            objconverter=tfs.release_events_to_json,
        ),
        F("catno", "labels.catalog_number"),
        F("laid", "labels.label.gid"),
        F("label", "labels.label.name"),
        F(
            "label_info_json",
            ["labels.catalog_number", "labels.label.gid", "labels.label.name"],
            objconverter=tfs.release_label_info_to_json,
        ),
        F("format", "mediums.format.name"),
        F("mediumid", "mediums.gid"),
        F("mediums", "medium_count", transformfunc=tfs.integer_sum, trigger=False),
        F("tracks", "mediums.track_count", transformfunc=sum),
        F("tracksmedium", "mediums.track_count", preserve_og=True),
        F(
            "medium_json",
            ["mediums.gid", "mediums.format.name", "mediums.cdtocs.id", "mediums.track_count"],
            objconverter=tfs.release_mediums_to_json,
        ),
        F("rgid", "release_group.gid"),
        F("rg_name", "release_group.name"),
        F("rg_comment", "release_group.comment"),
        F("primarytype", "release_group.type.name"),
        F("primarytype_gid", "release_group.type.gid"),
        F("secondarytype", "release_group.secondary_types.secondary_type.name", preserve_og=True),
        F(
            "secondarytype_gid",
            "release_group.secondary_types.secondary_type.gid",
            preserve_og=True,
        ),
        F(
            "calc_type",
            [
                "release_group.type.name",
                "release_group.type.gid",
                "release_group.secondary_types.secondary_type.name",
                "release_group.secondary_types.secondary_type.gid",
            ],
            objconverter=tfs.release_calc_type,
        ),
        F(
            "calc_type_gid",
            [
                "release_group.type.name",
                "release_group.type.gid",
                "release_group.secondary_types.secondary_type.name",
                "release_group.secondary_types.secondary_type.gid",
            ],
            objconverter=tfs.release_calc_type_gid,
        ),
        F("status", "status.name"),
        F("status_gid", "status.gid"),
        F("lang", "language.iso_code_3"),
        F("script", "script.iso_code"),
        F("quality", "quality"),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
    ],
    1.7,
)


SearchReleaseGroup = E(
    modelext.CustomReleaseGroup,
    [
        F("mbid", "gid"),
        F("releasegroup", "name"),
        F("comment", "comment"),
        F("arid", "artist_credit.artists.artist.gid", transformfunc=tfs.uuid_list_to_str_list),
        F("artist", "artist_credit.name"),
        F("artistname", "artist_credit.artists.artist.name"),
        F("creditname", "artist_credit.artists.name"),
        F(
            "artist_credit_json",
            [
                "artist_credit.gid",
                "artist_credit.name",
                "artist_credit.artists.name",
                "artist_credit.artists.join_phrase",
                "artist_credit.artists.artist.gid",
                "artist_credit.artists.artist.name",
                "artist_credit.artists.artist.comment",
                "artist_credit.artists.artist.sort_name",
                "artist_credit.artists.artist.aliases.name",
                "artist_credit.artists.artist.aliases.sort_name",
                "artist_credit.artists.artist.aliases.locale",
                "artist_credit.artists.artist.aliases.primary_for_locale",
                "artist_credit.artists.artist.aliases.begin_date",
                "artist_credit.artists.artist.aliases.end_date",
                "artist_credit.artists.artist.aliases.type.name",
                "artist_credit.artists.artist.aliases.type.id",
                "artist_credit.artists.artist.aliases.type.gid",
            ],
            objconverter=tfs.release_group_artist_credit_to_json,
        ),
        F("alias", "aliases.name"),
        F(
            "firstreleasedate",
            "first_release_date.first_release_date",
            transformfunc=tfs.index_partialdate_to_string,
        ),
        F("primarytype", "type.name"),
        F("primarytype_gid", "type.gid"),
        F("secondarytype", "secondary_types.secondary_type.name", preserve_og=True),
        F("secondarytype_gid", "secondary_types.secondary_type.gid", preserve_og=True),
        F(
            "calc_type",
            [
                "type.name",
                "type.gid",
                "secondary_types.secondary_type.name",
                "secondary_types.secondary_type.gid",
            ],
            objconverter=tfs.release_group_calc_type,
        ),
        F(
            "calc_type_gid",
            [
                "type.name",
                "type.gid",
                "secondary_types.secondary_type.name",
                "secondary_types.secondary_type.gid",
            ],
            objconverter=tfs.release_group_calc_type_gid,
        ),
        F("release", "releases.name"),
        F("reid", "releases.gid"),
        F("status", "releases.status.name"),
        F(
            "release_json",
            ["releases.gid", "releases.name", "releases.status.name", "releases.status.gid"],
            objconverter=tfs.release_group_releases_to_json,
        ),
        F("releases", "release_count", transformfunc=tfs.integer_sum, trigger=False),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
    ],
    1.7,
)


SearchSeries = E(
    modelext.CustomSeries,
    [
        F("mbid", "gid"),
        F("series", "name"),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F("alias", "aliases.name"),
        F(
            "alias_json",
            [
                "aliases.type.name",
                "aliases.type.id",
                "aliases.type.gid",
                "aliases.sort_name",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
            ],
            objconverter=tfs.aliases_to_json,
        ),
        F("comment", "comment"),
        F("tag", "tags.tag.name", preserve_og=True),
        F("tag_count", "tags.count", preserve_og=True),
    ],
    1.7,
)


SearchTag = E(
    models.Tag,
    [F("id", "id"), F("tag", "name")],
    1.7,
)


SearchUrl = E(
    modelext.CustomURL,
    [
        F("mbid", "gid"),
        F("url", "url"),
        F(
            "relationtype",
            ["artist_links.link.link_type.name", "release_links.link.link_type.name"],
        ),
        F("targetid", ["artist_links.entity0.gid", "release_links.entity0.gid"]),
        F(
            "targettype",
            ["artist_links.__tablename__", "release_links.__tablename__"],
            transformfunc=tfs.url_type,
        ),
        F(
            "rel_json",
            [
                "artist_links.entity0.gid",
                "artist_links.entity0.name",
                "artist_links.entity0.comment",
                "artist_links.entity0.sort_name",
                "artist_links.link.link_type.name",
                "artist_links.link.link_type.gid",
                "release_links.entity0.gid",
                "release_links.entity0.name",
                "release_links.entity0.comment",
                "release_links.link.link_type.name",
                "release_links.link.link_type.gid",
            ],
            objconverter=tfs.url_relations_to_json,
        ),
    ],
    1.7,
)


SearchWork = E(
    modelext.CustomWork,
    [
        F("mbid", "gid"),
        F("work", "name"),
        F("alias", "aliases.name"),
        F(
            "alias_json",
            [
                "aliases.type.name",
                "aliases.type.id",
                "aliases.type.gid",
                "aliases.sort_name",
                "aliases.locale",
                "aliases.primary_for_locale",
                "aliases.begin_date",
                "aliases.end_date",
            ],
            objconverter=tfs.aliases_to_json,
        ),
        F("arid", "artist_links.entity0.gid", transformfunc=tfs.uuid_list_to_str_list),
        F("artist", "artist_links.entity0.name"),
        F("recording", "recording_links.entity0.name"),
        F("rid", "recording_links.entity0.gid"),
        F(
            "rel_json",
            [
                "artist_links.entity0.gid",
                "artist_links.entity0.name",
                "artist_links.entity0.comment",
                "artist_links.entity0.sort_name",
                "artist_links.link.link_type.name",
                "artist_links.link.link_type.gid",
                "recording_links.entity0.gid",
                "recording_links.entity0.name",
                "recording_links.entity0.video",
                "recording_links.link.link_type.name",
                "recording_links.link.link_type.gid",
            ],
            objconverter=tfs.work_relations_to_json,
        ),
        F("comment", "comment"),
        F("iswc", "iswcs.iswc"),
        F("lang", "languages.language.iso_code_3", preserve_og=True),
        F("type", "type.name"),
        F("type_gid", "type.gid"),
        F("tag", "tags.tag.name"),
        F(
            "recording_count",
            "recording_links.entity0.gid",
            transformfunc=tfs.integer_count_all,
            trigger=False,
        ),
    ],
    1.7,
)


#: Maps core names to :class:`~sir.schema.searchentities.SearchEntity` objects.
SCHEMA = OrderedDict(sorted({
    # The dict gets sorted to guarantee a sorted order in `reindex`s --help
    "annotation": SearchAnnotation,
    "artist": SearchArtist,
    "area": SearchArea,
    "cdstub": SearchCDStub,
    "editor": SearchEditor,
    "event": SearchEvent,
    "instrument": SearchInstrument,
    "label": SearchLabel,
    "place": SearchPlace,
    "recording": SearchRecording,
    "release": SearchRelease,
    "release-group": SearchReleaseGroup,
    "series": SearchSeries,
    "tag": SearchTag,
    "url": SearchUrl,
    "work": SearchWork,
}.items(), key=lambda val: val[0]))


def generate_update_map():
    """
    Generates mapping from tables to Solr cores (entities) that depend on
    these tables and the columns of those tables. In addition provides a
    path along which data of an entity can be retrieved by performing a set
    of JOINs and a map of table names to SQLAlchemy ORM models and other useful
    mappings.

    Uses paths to determine the dependency.

    :rtype (dict, dict, dict, dict)
    """
    from sir.query_generation.paths import (
        last_model_in_path,
        second_last_model_in_path,
        unique_split_paths,
    )

    paths = defaultdict(set)
    column_map = defaultdict(set)

    # Used to map table names to mbdata.models for indexing.
    models = {}
    # Used to map table names to core names while handling entity deletion.
    core_map = {}

    for core_name, entity in SCHEMA.items():
        # Entity itself:
        # TODO(roman): See if the line below is necessary, if there is a better way to implement this.
        table_name = class_mapper(entity.model).persist_selectable.name
        core_map[table_name] = core_name
        paths[table_name].add((core_name, None))
        models[table_name] = entity.model
        # Related tables:
        for path in unique_split_paths([path for field in entity.fields
                                        for path in field.paths if field.trigger] + [path for path in entity.extrapaths or []]):
            model = last_model_in_path(entity.model, path)
            if model is not None:
                name = class_mapper(model).persist_selectable.name
                paths[name].add((core_name, path))
                if name not in models:
                    models[name] = model

            # For generating column map
            model, _ = second_last_model_in_path(entity.model, path)
            prop_name = path.split(".")[-1]
            try:
                prop = getattr(model, prop_name).prop
                # We only care about columns, not relations
                if isinstance(prop, (ColumnProperty, CompositeProperty)):
                    # In case of Composite properties, there might be more
                    # than 1 columns involved
                    column_names = [col.name for col in prop.columns]
                    column_map[model.__table__.name].update(column_names)
                elif isinstance(prop, RelationshipProperty):
                    if prop.direction.name == 'MANYTOONE':
                        # We are assuming MB-DB uses only non-composite FKs.
                        # In case this changes in the future, `test.DBTest.test_non_composite_fk`
                        # will fail.
                        column_map[model.__table__.name].add(list(prop.local_columns)[0].name)
            # This happens in case of annotation and url paths
            # which have path to figure out the table name via transform funcs
            except AttributeError:
                pass
    return dict(paths), dict(column_map), models, core_map
